# Generated by Django 4.2.1 on 2023-05-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_manufacturer_delete_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
